#!/usr/bin/env bash

# Store the source and destination
src=""$HOME"/Library/Application Support/Firefox/Profiles/"
dest=""$HOME"/Documents/firefox-backup"

# Prepare the destination directory
mkdir -p "$dest"

# Copy all the Firefox profiles to the destination
cp -pRfiv "$src" "$dest"
